name: Update GitHub Profile

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variables
        run: |
          echo "GITHUB_TOKEN=${{ secrets.PAT_TOKEN }}" >> $GITHUB_ENV
          echo "GITHUB_USERNAME=${{ secrets.USERNAME }}" >> $GITHUB_ENV

      - name: Fetch Contributions
        run: python scripts/fetch_contributions.py

      - name: Render Heatmap
        run: python scripts/render_heatmap_svg.py

      - name: Build README
        run: python scripts/build_readme.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add README.md images/ data/

          git diff --cached --quiet || git commit -m "Auto-update GitHub profile"

          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git

          git push origin main